# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Blog Title', max_length=2048)),
                ('content', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=2048, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
