# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[(b'ro', b'RO'), (b'en', b'EN')], default=b'ro', max_length=8),
        ),
    ]
